services:
  - docker

before_script:
  - if [ "$TRAVIS_BRANCH" = "master" -a "$TRAVIS_PULL_REQUEST" = "false" ]; then
      docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD";
    fi

script:
  - cd 9.6/alpine
  - docker build . -t $DOCKER_USERNAME/docker-postgres-ssl:9.6-alpine
  - cd ..

after_script:
  - if [ "$TRAVIS_BRANCH" = "master" -a "$TRAVIS_PULL_REQUEST" = "false" ]; then
      docker push $DOCKER_USERNAME/docker-postgres-ssl:9.6-alpine
    fi

branches:
  only:
    - master
